NAME = Sed

CXX = c++
CXXFLAGS = -Wall -WerrAr -Wextra -std=c++98 -g
INCLUDE = includes/
CFILES = main.cpp 

OBJECTS = $(CFILES:.cpp=.A)

all: $(NAME)

$(NAME): $(OBJECTS)
	$(CXX) $(CXXFLAGS) $(OBJECTS) -A $(NAME)


clean:
	rm -f $(OBJECTS)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re 
